const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'});
 const page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const base='http://127.0.0.1:3000';
 const artifacts=path.join(__dirname,'../artifacts');await fs.mkdir(artifacts,{recursive:true});
 const noOverflow=async()=>assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 const ready=async()=>{await page.locator('#nk-choose-preset').click();await page.locator('#nk-checkout').click();};
 try{
  await page.goto(base+'/noir.html?offer=10&utm_source=test');await page.evaluate(()=>document.fonts.ready);await noOverflow();
  assert(await page.locator('#nk-hero-image').evaluate(img=>img.complete&&img.naturalWidth>0));
  await page.screenshot({path:path.join(artifacts,'noir-mobile.png')});
  await page.locator('[data-hero="tygar"]').click();assert.equal(await page.locator('#nk-hero-name').textContent(),'Tygar');
  await ready();assert(await page.locator('#nk-order').evaluate(el=>el.open));
  await page.locator('#nk-name').fill('Тест');await page.locator('#nk-phone').fill('123');await page.locator('[name=consent]').check();await page.locator('[type=submit]').click();
  assert.equal(await page.locator('#nk-phone').evaluate(el=>el.checkValidity()),false);
  await page.locator('#nk-phone').fill('87771234567');await page.locator('[type=submit]').click();
  assert((await page.locator('#nk-order-result').textContent()).includes('Контакты никуда не отправлены'));
  await page.locator('#nk-result-close').click();await page.waitForFunction(()=>document.body.style.overflow==='');
  assert(!(await page.evaluate(()=>JSON.stringify(localStorage))).includes('7771234567'));
  console.log('PASS ready sets, hero switching, phone validation, demo and no contact persistence');
  await page.locator('[data-offer-choice="5"]').click();await page.locator('[data-mode="custom"]').click();
  for(let i=0;i<5;i++)await page.locator('[data-add="imagination"]').click();
  assert(await page.locator('[data-add="tygar"]').isDisabled());
  await page.locator('[data-box="1"]').click();assert(await page.locator('#nk-gift-mirror').isVisible());
  await page.locator('#nk-edit-first').click();await page.locator('[data-remove-index="0"]').click();
  assert.equal(await page.locator('#nk-progress-count').textContent(),'4 / 5');
  await page.locator('[data-add="tygar"]').click();await page.reload();
  await page.locator('#nk-dock-action').click();
  const summary=await page.locator('#nk-order-summary p').allTextContents();assert.equal(summary[0].split('мл')[1],summary[1].split('мл')[1]);
  await page.locator('#nk-close-order').click();await page.locator('[data-mode="custom"]').click();
  await page.locator('.nk-custom-top').evaluate(el=>el.scrollIntoView({block:'start'}));
  await page.screenshot({path:path.join(artifacts,'noir-builder.png')});
  console.log('PASS custom repetitions, five-slot limit, mirrored gift and persistence');
  await page.locator('[data-offer-choice="10"]').click();await page.locator('[data-mode="custom"]').click();
  await page.locator('[data-box="1"]').click();await page.locator('[data-remove-index="0"]').click();
  assert.equal(await page.locator('#nk-progress-count').textContent(),'4 / 5');
  await page.locator('[data-box="0"]').click();assert.equal(await page.locator('#nk-progress-count').textContent(),'5 / 5');
  await page.locator('[data-box="1"]').click();await page.locator('[data-add="pheramone"]').click();
  console.log('PASS independent second set in offer 10');
  await page.setViewportSize({width:320,height:740});await noOverflow();
  await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/noir.html?offer=10');await page.evaluate(()=>document.fonts.ready);await noOverflow();
  await page.screenshot({path:path.join(artifacts,'noir-desktop.png')});
  await page.screenshot({path:path.join(artifacts,'noir-full.png'),fullPage:true});
  for(const offer of ['5','10']){await page.goto(base+`/dist/preview-${offer}.html`);await page.evaluate(()=>document.fonts.ready);assert.equal(await page.locator('#killer-perfume').getAttribute('data-offer'),offer);assert((await page.locator('#nk-hero-image').getAttribute('src')).startsWith('data:image/webp'));await noOverflow();}
  await page.goto(base+'/dist/tilda-10.html');await page.locator('[data-mode=custom]').click();await page.locator('#nk-scent-track').scrollIntoViewIfNeeded();
  assert(await page.locator('.nk-scent-photo img').first().evaluate(img=>img.complete&&img.naturalWidth>0));
  console.log('PASS 320px / 390px / desktop layouts and both exports');
  await page.addInitScript(()=>{window.attempts=0;window.leads=0;document.addEventListener('kp:lead_submitted',()=>window.leads++);window.KILLER_PERFUME_CONFIG={submitLead:async payload=>{window.payload=payload;if(++window.attempts===1)throw new Error('test');return{ok:true};}};});
  await page.goto(base+'/noir.html?offer=5&utm_source=smoke');await ready();
  await page.locator('#nk-name').fill('Тест');await page.locator('#nk-phone').fill('+77771234567');await page.locator('[name=consent]').check();await page.locator('[type=submit]').click();
  await page.locator('#nk-form-error').filter({hasText:'Не удалось'}).waitFor();assert.equal(await page.evaluate(()=>window.leads),0);
  await page.locator('[type=submit]').click();await page.locator('#nk-order-result').filter({hasText:'ПРИНЯТА'}).waitFor();
  const result=await page.evaluate(()=>({payload:window.payload,leads:window.leads}));assert.equal(result.leads,1);assert.equal(result.payload.attribution.utm_source,'smoke');assert.equal(result.payload.priceKzt,50000);assert.deepEqual(result.payload.sets[0],result.payload.sets[1]);
  assert.deepEqual(errors,[]);console.log('PASS receiver error/retry, confirmed lead event, payload and no browser errors');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
